# Site settings
title: Freelance Services
description: Software Development & Consulting

# Build settings
# theme: default
theme: jekyll-theme-cayman
markdown: kramdown

# LinkedIn
show_linkedin: true
linkedin_url: https://www.linkedin.com/in/basbiezemans

# Plugins
# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag