# Site settings
title: Freelance Services
description: Software Development & Consulting

# Build settings
# theme: default
theme: jekyll-theme-cayman
markdown: kramdown

# Plugins
# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag